improve pre-commit check

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,11 +4,24 @@ if [ "${DEEPOPS_BYPASS_LINT}" ]; then
 	exit 0
 fi
 
+FAILED=0
+
 # Lint changed Ansible files
-.githooks/check-ansible.py
+if ! .githooks/check-ansible.py; then
+	FAILED=1
+	echo "Failed Ansible lint"
+fi
 
 # Lint changed shell scripts
-.githooks/check-shell.py
+if ! .githooks/check-shell.py; then
+	FAILED=1
+	echo "Failed shell lint"
+fi
 
 # Lint changed Python files
-.githooks/check-python.py
+if ! .githooks/check-python.py; then
+	FAILED=1
+	echo "Failed python lint"
+fi
+
+exit ${FAILED}
