updates

diff --git a/deepops b/deepops
--- a/deepops
+++ b/deepops
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+ROOK_VERSION=v0.9.0-66.g80b2451
+
 #host_path=${DEEPOPS_HOST_ROOT_PATH:-`pwd`}
 host_path=${DEEPOPS_HOST_ROOT_PATH:-/tmp/deepops}
 container=${DEEPOPS_CONTAINER:-deepops/deploy:latest}
@@ -8,12 +10,52 @@ docker="docker run --rm -ti --net=host"
 docker_mnt_config="-v ${host_path}/config:/source/deepops/config"
 docker_mnt_ssh="-v ${host_path}/ssh:/root/.ssh"
 
+failed=
+
+## Container wrappers
+run_root() {
+    ${docker} ${docker_mnt_config} ${docker_mnt_ssh} -e KUBECONFIG=/source/deepops/config/admin.conf ${container} "$@"
+}
+
+run_user() {
+    ${docker} -u $(id -u):$(id -g) ${docker_mnt_config} ${docker_mnt_ssh} -e KUBECONFIG=/source/deepops/config/admin.conf ${container} "$@"
+}
+
+## Binary overrides
 kubectl() {
-    ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} kubectl --kubeconfig=/source/deepops/config/admin.conf $@
+    run_user kubectl $@
 }
 
 helm() {
-    ${docker} ${docker_mnt_config} ${docker_mnt_ssh} -e KUBECONFIG=/source/deepops/config/admin.conf ${container} helm --home /source/deepops/config/.helm $@
+    if ! [ -d ${host_path}/config/.helm ] ; then
+        run_user helm --home /source/deepops/config/.helm init --client-only
+    fi
+    run_root helm --home /source/deepops/config/.helm $@
+}
+
+## Install functions
+install_k8s() {
+    run_root ansible-playbook -b -i config/kube-mgmt-hosts.ini --extra-vars "@config/kube.yml" kubespray/cluster.yml
+    if [ $? -ne 0 ] ; then
+        echo "Failed to install Kubernetes"
+        failed=1
+    fi
+    run_root ansible all -i config/kube-mgmt-hosts.ini -b -m fetch -a "src=/etc/kubernetes/admin.conf flat=yes dest=./config/"
+    echo
+    kubectl get nodes
+}
+
+install_rook() {
+    helm ls --all rook-ceph | grep DEPLOYED
+    if [ $? -ne 0 ] ; then
+        helm repo add rook-master https://charts.rook.io/master
+        helm install --namespace rook-ceph-system --name rook-ceph rook-master/rook-ceph --version ${ROOK_VERSION} --set agent.flexVolumeDirPath=/var/lib/kubelet/volume-plugins/
+        kubectl create -f services/rook-cluster.yml
+        if [ $? -ne 0 ] ; then
+            echo "Failed to install Rook"
+            failed=1
+        fi
+    fi
 }
 
 logo() {
@@ -56,7 +98,7 @@ if [ $? -ne 0 ] ; then
 fi
 
 case "$1" in
-    bootstrap)
+    install)
         shift
 
         mkdir -p ${host_path}
@@ -108,11 +150,6 @@ case "$1" in
 
         # run bootstrap playbook
         case "$1" in
-            mgmt)
-                shift
-                echo
-                ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} setup_deepops_user ${ssh_key} "$@"
-                ;;
             compute)
                 shift
                 echo
@@ -125,58 +162,59 @@ case "$1" in
                 done
                 set -x
                 args=$(echo $@ | sed 's/--bastion//g')
-                ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} setup_deepops_user ${ssh_key} ${bastion} ${args}
+                run_root setup_deepops_user ${ssh_key} ${bastion} ${args}
                 set +x
+                ;;
+            *)
+                echo
+                echo "Bootstrapping systems"
+                run_root setup_deepops_user ${ssh_key} "$@"
+                if [ $? -ne 0 ] ; then
+                    echo "Failed to bootstrap"
+                    failed=1
+                fi
                 ;;
         esac
         
+        # install k8s
+        if [ ! $failed ] ; then
+            echo "Installing Kubernetes"
+            install_k8s
+        fi
+
+        # install rook
+        if [ ! $failed ] ; then
+            echo "Installing Rook"
+            install_rook
+        fi
+
         # remove copied ssh private key
         if [ -f ${host_path}/ssh/bootstrap_rsa ] ; then
             rm -f ${host_path}/ssh/bootstrap_rsa
             echo -e "Removed SSH key:\t\t${host_path}/ssh/bootstrap_rsa"
         fi
         ;;
-    k8s|kube|kubernetes)
-        ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} ansible-playbook -b -i config/kube-mgmt-hosts.ini --extra-vars "@config/kube.yml" kubespray/cluster.yml
-        ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} ansible -i config/kube-mgmt-hosts.ini all -b -m fetch -a "src=/etc/kubernetes/admin.conf flat=yes dest=./config/"
-        #if [ -f ./kubectl ] ; then
-            #curl -sLO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
-            #chmod +x ./kubectl
-        #fi
-        #mv ~/.kube/config{,.bak} && KUBECONFIG=./config/admin.conf:~/.kube/config.bak ./kubectl config view --flatten | tee ~/.kube/config >/dev/null
-        echo
-        #./kubectl get nodes
-        kubectl get nodes
-        ;;
     slurm)
         ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} ansible-playbook -k -K ansible/playbooks/slurm.yml
         ;;
-    bash)
-        ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} bash
+    shell)
+        run_root bash
         ;;
     cmd)
         shift
-        ${docker} ${docker_mnt_config} ${docker_mnt_ssh} ${container} $@
+        run_root $@
         ;;
     helm)
         shift
-        if ! [ -d ${host_path}/config/.helm ] ; then
-            ${docker} -u $(id -u):$(id -g) ${docker_mnt_config} ${docker_mnt_ssh} -e KUBECONFIG=/source/deepops/config/admin.conf ${container} helm --home /source/deepops/config/.helm init --client-only
-        fi
         helm $@
         ;;
     kubectl)
         shift
         kubectl $@
         ;;
-    ceph)
-        helm repo add rook-master https://charts.rook.io/master
-        helm install --namespace rook-ceph-system --name rook-ceph rook-master/rook-ceph --version v0.7.0-284.g863c10f --set agent.flexVolumeDirPath=/var/lib/kubelet/volume-plugins/
-        kubectl create -f services/rook-cluster.yml
-        ;;
     *)
         logo
-        echo "Usage: $0 bootstrap [OPTIONS]"
+        echo "Usage: $0 install [OPTIONS]"
         echo
         ${docker} ${container} setup_deepops_user --help | tail -n+3 | grep -v ssh
         echo "Environment variables:"
