Enable rootless docker-daemon per Slurm job.

diff --git a/roles/slurm/templates/etc/slurm/epilog.d/95-lastuserjob-rootless b/roles/slurm/templates/etc/slurm/epilog.d/95-lastuserjob-rootless
--- a/roles/slurm/templates/etc/slurm/epilog.d/95-lastuserjob-rootless
+++ b/roles/slurm/templates/etc/slurm/epilog.d/95-lastuserjob-rootless
@@ -1,3 +1,19 @@
 #!/usr/bin/env bash
+
 command -v singularity || exit 0
 /usr/local/bin/singularity config fakeroot -r "${SLURM_JOB_USER}" || true
+
+# clean up rootless docker /var/tmp/userid-${SLURM_JOB_UID}-jobid-${SLURM_JOB_ID}
+
+dockerdpid=$(lsof -a -u ${SLURM_JOB_UID} +D ${DOCKER_DATAROOT} \
+  -d mem -c dockerd -t 2>/dev/null | head -n1)
+
+if [ ! -z "${dockerdpid}" ]; then
+    kill ${dockerdpid} || true
+fi
+
+user_vartmp_dir="/var/tmp/userid-${SLURM_JOB_UID}-jobid-${SLURM_JOB_ID}"
+
+if [ -d "${user_vartmp_dir}" ]; then
+    rm -rf "${user_vartmp_dir}"
+fi
